import type { Technique } from './techniques'
import type { WeeklyPost } from './weeklyPosts'
import type { Student } from './users'

export const mockTechniques: Technique[] = [
  {
    id: 'tech-1',
    gymId: 'gym-1',
    title: 'Armbar from Guard',
    description:
      'Classic submission from closed guard. Isolate the arm, break posture, hip out, and extend.',
    position: 'guard',
    beltLevel: 'white',
    type: 'submission',
    difficulty: 2,
    videoUrl: null,
    thumbnailUrl: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'tech-2',
    gymId: 'gym-1',
    title: 'Triangle Choke',
    description:
      'Lock a triangle with your legs around the opponent\'s neck and one arm. Squeeze for the tap.',
    position: 'guard',
    beltLevel: 'white',
    type: 'submission',
    difficulty: 3,
    videoUrl: null,
    thumbnailUrl: null,
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'tech-3',
    gymId: 'gym-1',
    title: 'Rear Naked Choke',
    description:
      'From back control, secure the seatbelt grip, slide arm under chin, lock in figure-four.',
    position: 'back',
    beltLevel: 'blue',
    type: 'submission',
    difficulty: 2,
    videoUrl: null,
    thumbnailUrl: null,
    createdAt: '2024-01-17T10:00:00Z',
    updatedAt: '2024-01-17T10:00:00Z',
  },
]

export const mockPosts: WeeklyPost[] = [
  {
    id: 'post-1',
    gymId: 'gym-1',
    instructorId: 'user-1',
    title: 'Week 3: Guard Retention Fundamentals',
    body: 'This week we focus on keeping your guard intact against passes. We\'ll cover hip movement, framing, and recovery.',
    status: 'published',
    techniqueIds: ['tech-1', 'tech-2'],
    targetBelt: 'white',
    scheduledAt: null,
    publishedAt: '2024-01-15T08:00:00Z',
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'post-2',
    gymId: 'gym-1',
    instructorId: 'user-1',
    title: 'Advanced Back Attacks — Draft',
    body: 'Exploring the back attack system: entries, control, and finishes.',
    status: 'draft',
    techniqueIds: ['tech-3'],
    targetBelt: 'blue',
    scheduledAt: null,
    publishedAt: null,
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
]

export const mockStudents: Student[] = [
  {
    id: 'student-1',
    gymId: 'gym-1',
    name: 'Marcus Webb',
    email: 'marcus@example.com',
    belt: 'blue',
    avatarUrl: null,
    techniquesLogged: 24,
    lastActiveAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    flowchartNodes: 12,
    joinedAt: '2023-06-01T00:00:00Z',
  },
  {
    id: 'student-2',
    gymId: 'gym-1',
    name: 'Sofia Reyes',
    email: 'sofia@example.com',
    belt: 'purple',
    avatarUrl: null,
    techniquesLogged: 61,
    lastActiveAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    flowchartNodes: 34,
    joinedAt: '2022-03-15T00:00:00Z',
  },
  {
    id: 'student-3',
    gymId: 'gym-1',
    name: 'David Kim',
    email: 'david@example.com',
    belt: 'white',
    avatarUrl: null,
    techniquesLogged: 8,
    lastActiveAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    flowchartNodes: 4,
    joinedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'student-4',
    gymId: 'gym-1',
    name: 'Aisha Nkosi',
    email: 'aisha@example.com',
    belt: 'blue',
    avatarUrl: null,
    techniquesLogged: 33,
    lastActiveAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    flowchartNodes: 18,
    joinedAt: '2023-02-20T00:00:00Z',
  },
  {
    id: 'student-5',
    gymId: 'gym-1',
    name: 'Ryan Torres',
    email: 'ryan@example.com',
    belt: 'white',
    avatarUrl: null,
    techniquesLogged: 5,
    lastActiveAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    flowchartNodes: 2,
    joinedAt: '2024-01-10T00:00:00Z',
  },
]
